# Generated by Django 5.1.3 on 2024-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Animal_Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Item_Category',
        ),
        migrations.AddField(
            model_name='product',
            name='Animal_Category',
            field=models.ManyToManyField(to='api.animal_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Item_Category',
            field=models.ManyToManyField(to='api.item_category'),
        ),
    ]
