services:
  backend:
    build:
      context: ./Backend/petopia
      dockerfile: dockerfile
    container_name: backend
    command: >
          sh -c "python manage.py makemigrations && python manage.py makemigrations api && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend/petopia:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/petopia
    container_name: frontend
    command: npm run dev
    volumes:
      - ./Frontend/petopia:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  postgres_data: